language: go
go: 1.5

sudo: false

notifications:
  email: false

before_install:
  - go version
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -t -d -v ./...
  - go build -v ./...

script:
  - sh test_cover.sh

after_successs:
  - goveralls -coverprofile=.profile.cov -repotoken $COVERALLS_TOKEN
