language: go
go:
  - 1.4.3
  - 1.5.3
  - 1.6

sudo: false

notifications:
  email: false

before_install:
  - go version
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover

install:
  - go get -t -d -v ./...
  - go build -v ./...

script:
  - gotestcover -v -covermode=count -coverprofile=.profile.cov -parallelpackages=1 ./...

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.6" ]; then goveralls -coverprofile=.profile.cov -repotoken $COVERALLS_TOKEN; fi
